convert CardBack.png CardBack.png
convert PenguinCard.png PenguinCard.png
convert CatCard.png CatCard.png
convert CarCard.png CarCard.png
convert RainbowCard.png RainbowCard.png
convert StarCard.png StarCard.png
convert IceCreamCard.png IceCreamCard.png
convert FlowerCard.png FlowerCard.png
convert BearCard.png BearCard.png
