sips --resampleWidth 640 "Silvergate.jpg" --out "Silvergate.jpg"
sips --resampleWidth 640 "Skyline.jpg" --out "Skyline.jpg"
sips --resampleWidth 640 "Summit.jpg" --out "Summit.jpg"
sips --resampleWidth 640 "Woodglen.jpg" --out "Woodglen.jpg"
sips --resampleWidth 640 "Falcon Hill.jpg" --out "Falcon Hill.jpg"
sips --resampleWidth 640 "Greenfield.jpg" --out "Greenfield.jpg"
sips --resampleWidth 640 "Heritage.jpg" --out "Heritage.jpg"
sips --resampleWidth 640 "Hermosa Vista.jpg" --out "Hermosa Vista.jpg"
sips --resampleWidth 640 "Holmes.jpg" --out "Holmes.jpg"
sips --resampleWidth 640 "Jefferson.jpg" --out "Jefferson.jpg"
sips --resampleWidth 640 "Kingsborough.jpg" --out "Kingsborough.jpg"
sips --resampleWidth 640 "Kleinman.jpg" --out "Kleinman.jpg"
sips --resampleWidth 640 "Los Alamos.jpg" --out "Los Alamos.jpg"
sips --resampleWidth 640 "Meadowgreen.jpg" --out "Meadowgreen.jpg"
sips --resampleWidth 640 "Monterey.jpg" --out "Monterey.jpg"
sips --resampleWidth 640 "Park of the Cannels.jpg" --out "Park of the Cannels.jpg"
sips --resampleWidth 640 "Pequeno.jpg" --out "Pequeno.jpg"
sips --resampleWidth 640 "Pioneer.jpg" --out "Pioneer.jpg"
sips --resampleWidth 640 "Quail Run.jpg" --out "Quail Run.jpg"
sips --resampleWidth 640 "Red Mountain.jpg" --out "Red Mountain.jpg"
sips --resampleWidth 640 "Riverview.jpg" --out "Riverview.jpg"
sips --resampleWidth 640 "Sherwood.jpg" --out "Sherwood.jpg"
sips --resampleWidth 640 "Emerald.jpg" --out "Emerald.jpg"
sips --resampleWidth 640 "Evergreen.jpg" --out "Evergreen.jpg"
sips --resampleWidth 640 "Falcon Field.jpg" --out "Falcon Field.jpg"
sips --resampleWidth 640 "countryside.jpg" --out "countryside.jpg"
sips --resampleWidth 640 "compressPng.sh" --out "compressPng.sh"
sips --resampleWidth 640 "Park Images.zip" --out "Park Images.zip"
sips --resampleWidth 640 "Alta Mesa.jpeg" --out "Alta Mesa.jpeg"
sips --resampleWidth 640 "Augusta Ranch.jpeg" --out "Augusta Ranch.jpeg"
sips --resampleWidth 640 "Beverly.jpeg" --out "Beverly.jpeg"
sips --resampleWidth 640 "Candlelight.JPG" --out "Candlelight.JPG"
sips --resampleWidth 640 "Carriage.jpeg" --out "Carriage.jpeg"
sips --resampleWidth 640 "Chaparral.jpeg" --out "Chaparral.jpeg"
sips --resampleWidth 640 "Chelsea.jpeg" --out "Chelsea.jpeg"
sips --resampleWidth 640 "Desert Trails.jpg" --out "Desert Trails.jpg"
sips --resampleWidth 640 "Dobson Ranch.jpeg" --out "Dobson Ranch.jpeg"
sips --resampleWidth 640 "Eastmark Great.jpg" --out "Eastmark Great.jpg"
sips --resampleWidth 640 "Enid.jpeg" --out "Enid.jpeg"
sips --resampleWidth 640 "Ensenada.jpeg" --out "Ensenada.jpeg"
sips --resampleWidth 640 "Escobedo.jpeg" --out "Escobedo.jpeg"
sips --resampleWidth 640 "Fitch.jpeg" --out "Fitch.jpeg"
sips --resampleWidth 640 "Gateway.jpeg" --out "Gateway.jpeg"
sips --resampleWidth 640 "Gene Autry.jpg" --out "Gene Autry.jpg"
sips --resampleWidth 640 "Golden Hills.jpeg" --out "Golden Hills.jpeg"
sips --resampleWidth 640 "Guerrero.jpeg" --out "Guerrero.jpeg"
sips --resampleWidth 640 "Harmony.jpeg" --out "Harmony.jpeg"
sips --resampleWidth 640 "Mountain View.jpeg" --out "Mountain View.jpeg"
sips --resampleWidth 640 "Palo Verde.jpeg" --out "Palo Verde.jpeg"
sips --resampleWidth 640 "Porter.jpeg" --out "Porter.jpeg"
sips --resampleWidth 640 "Princess.jpeg" --out "Princess.jpeg"
sips --resampleWidth 640 "Rancho del Mar.jpeg" --out "Rancho del Mar.jpeg"
sips --resampleWidth 640 "Reed.jpg" --out "Reed.jpg"
sips --resampleWidth 640 "Sheepherders.jpeg" --out "Sheepherders.jpeg"
sips --resampleWidth 640 "Stapley.jpeg" --out "Stapley.jpeg"
sips --resampleWidth 640 "Valencia.jpeg" --out "Valencia.jpeg"
sips --resampleWidth 640 "Vista Monterey.jpeg" --out "Vista Monterey.jpeg"
sips --resampleWidth 640 "Washington.jpeg" --out "Washington.jpeg"
